# Global value here is just for declaration so chart can be debugged in isolation, 
# default global value will be set by parent chart and is initialised in bootstrap helm chart
global:
  env:
  branch:
  ingressConfig:
    ingress:
    annotations:
      cert-manager.io/cluster-issuer:
      argocd.argoproj.io/sync-wave:
    tlsSecretName:

argocdDomain: "argocd2.shivamjha.com"
