apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cert
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: info@shivamjha.com # Email for ACME registration
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
      - dns01:
          cloudflare:
            email: info@shivamjha.com
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: token-secret
        selector:
          dnsZones:
            - "shivamjha.com"
