apiVersion: v1
kind: ConfigMap
metadata:
  name: auth
  namespace: container-registry
data:
  htpasswd: |
    shivam:$apr1$wt6S0vfY$XnjgFwsRisSTvXNWSzk.C.
    shivam2:$apr1$YdwbGxuQ$8xdbdViIIpn2c3FowpS3g/

---
