# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: auth
#   namespace: container-registry
# data:
#   htpasswd: |
#     shivam:$apr1$wt6S0vfY$XnjgFwsRisSTvXNWSzk.C.
#     shivam2:$apr1$YdwbGxuQ$8xdbdViIIpn2c3FowpS3g/
# ---
# apiVersion: extensions/v1beta1
# kind: Deployment
# metadata:
#   name: registry
#   namespace: container-registry
# spec:
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: registry
#     spec:
#       containers:
#         image: registry:2
#         name: registry
#         ports:
#           - containerPort: 5000
#         - env:
#           - name: REGISTRY_AUTH
#             value: htpasswd
#           - name: REGISTRY_AUTH_HTPASSWD_PATH
#             value: /auth/htpasswd
#           - name: REGISTRY_AUTH_HTPASSWD_REALM
#             value: Registry Realm
#           - name: REGISTRY_STORAGE
#             value: s3
#           - name: REGISTRY_STORAGE_S3_BUCKET
#             value: shivam-test-3
#           - name: REGISTRY_STORAGE_S3_ACCESSKEY
#             valueFrom:
#               secretKeyRef:
#                 name: s3-secret
#                 key: access-key
#           - name: REGISTRY_STORAGE_S3_SECRETKEY
#             valueFrom:
#               secretKeyRef:
#                 name: s3-secret
#                 key: secret-key

#           volumeMounts:
#             - name: auth
#               mountPath: /auth
#       volumes:
#         - name: auth
#           configMap:
#             name: auth
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: registry
#   namespace: container-registry
# spec:
#   ports:
#     - port: 3000
#       targetPort: 5000
#   selector:
#     app: registry
