apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-argocd
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cert"
    argocd.argoproj.io/sync-wave: "2"
  labels:
    type: reverse-proxy
spec:
  ingressClassName: "haproxy"
  tls:
    - secretName: cert-tls
      hosts:
        - {{ .Values.argocdDomain }}
  rules:
    - host: {{ .Values.argocdDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
