apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-argocd
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cert"
    kubernetes.io/ingress.class: "nginx"
    argocd.argoproj.io/sync-wave: "2"
  labels:
    type: reverse-proxy
spec:
  tls:
    - secretName: cert-tls
      hosts:
        - "argocd.shivamjha.com"
  rules:
    - host: argocd.shivamjha.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
