apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-argocd
  namespace: argocd
  annotations:
    {{ toYaml $.Values.global.ingressConfig.annotations | nindent 4 }}
spec:
  ingressClassName: {{ $.Values.global.ingressConfig.ingress }}
  tls:
    - secretName: {{ $.Values.global.ingressConfig.tlsSecretName }}
      hosts:
        - {{ .Values.argocdDomain }}
  rules:
    - host: {{ .Values.argocdDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
