apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: shared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-replica
  template:
    metadata:
      name: redis-pod
      labels:
        app: redis-replica
    spec:
      containers:
        - name: redis-container
          image: redis:alpine3.18
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: shared
spec:
  selector:
    app: redis-replica
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
