global:
  logLevel: 0 # Set the verbosity of cert-manager. Range of 0 - 6 with 6 being the most verbose.

installCRDs: true

replicaCount: 1

webhook:
  replicaCount: 1

cainjector:
  enabled: true
  replicaCount: 1
