apiVersion: v1
kind: Service
metadata:
  name: hello-k8-service_1
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    app: hello-k8
  type: ClusterIP # default
  ports:
    - port: 8000
      targetPort: 8080
