{{ range $name, $value  := .Values.helmCharts }}
{{ if $value.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $name }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: {{ $value.syncWave | quote }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: {{ $value.repoURL }}
      {{ if $value.chart }}
      chart: {{ $value.chart }}
      targetRevision: {{ $value.version  }}
      {{ end }}
      {{ if $value.path }}
      path: {{ $value.path }}
      targetRevision: {{ $.Values.global.branch  }}
      {{ end }}
      helm:
        values: |
          global:
            {{ toYaml $.Values.global | nindent 12 }}
        valueFiles:
          # Include dev value if it our custom helm repo chart
          {{ if and (eq $.Values.global.env "dev") (not $value.chart) }} 
            - values.dev.yaml
          {{ end }}
          {{ if $value.valueFile }}
            - $values{{ $value.valueFile.path }}
          {{ end }}
        # {{ if $value.parameters }}
        # parameters:
        #    {{ range $key, $val  := $value.parameters }}
        #       - name : {{ $key }}
        #         value: "{{ $val }}"  
        #    {{ end }}
        # {{ end }}
    {{ if $value.valueFile }}
    - repoURL: {{ $value.valueFile.repoURL }}
      targetRevision: {{ $.Values.global.env }}
      ref: values
    {{ end }}
  destination:
    namespace: {{ $value.namespace }}
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{ end }}
{{ end }}