{{ range $i, $app  := .Values.helmCharts }}
{{ if $app.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app.name }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: {{ $i | quote }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: {{ $app.repoURL }}
      {{ if $app.chart }}
      chart: {{ $app.chart }}
      {{ end }}
      {{ if $app.path }}
      path: {{ $app.path }}
      {{ end }}
      targetRevision: {{ $app.version | $app.branch | default "HEAD"  }}
      helm:
        values: |
          global:
            {{ toYaml $.Values.global | nindent 12 }}
        valueFiles:
          {{ if eq $.Values.global.env "dev" }}
            - values.dev.yaml
          {{ end }}
          {{ if $app.valueFile }}
            - $values{{ $app.valueFile.path }}
          {{ end }}
        # {{ if $app.parameters }}
        # parameters:
        #    {{ range $key, $val  := $app.parameters }}
        #       - name : {{ $key }}
        #         value: "{{ $val }}"  
        #    {{ end }}
        # {{ end }}
    {{ if $app.valueFile }}
    - repoURL: {{ $app.valueFile.repoURL }}
      targetRevision: {{ $.Values.global.env }}
      ref: values
    {{ end }}
  destination:
    namespace: {{ $app.namespace }}
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{ end }}
{{ end }}