applications:
  - name: hello-k8
    imageName: "paulbouwer/hello-kubernetes:1.10.1"
    containerPort: 8080
    replicas: 2
    host: k9.shivamjha.com
    env:
      MESSAGE: "Hello from Helm"
  # - name: metabase
  #   imageName: "metabase/metabase:v0.46.5"
  #   containerPort: 3000
  #   replicas: 1
  #   host: metabase.shivamjha.com


ingressConfig:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cert"
    kubernetes.io/ingress.class: "nginx"
    argocd.argoproj.io/sync-wave: "3"
  tlsSecretName: "cert-tls"
