# Global value here is just for declaration so chart can be debugged in isolation,
# default global value will be set by parent chart and is initialised in bootstrap helm chart
global:
  env:
  branch:
  ingressConfig:
    ingress:
    annotations:
      cert-manager.io/cluster-issuer:
    tlsSecretName:

applications:
  hello-k8:
    imageName: "containers.shivamjha.com/private-container:0.0.2" # private copy of "paulbouwer/hello-kubernetes:1.10.1"
    containerPort: 8080
    replicas: 2
    host: k3.shivamjha.com
    env:
      MESSAGE: "Hello from Helm - Prod Environment"
    syncWave: 1
    port: 1000
  container-registry:
    imageName: "registry:2.8.2"
    containerPort: 5000
    replicas: 1
    host: containers.shivamjha.com
    syncWave: 1
    port: 1001
    env:
      REGISTRY_AUTH: "htpasswd"
      REGISTRY_AUTH_HTPASSWD_PATH: "/auth/htpasswd"
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_STORAGE: "s3"
      REGISTRY_STORAGE_S3_BUCKET: "shivam-test-3"
      REGISTRY_STORAGE_S3_REGION: "ap-south-1"
    secrets:
      REGISTRY_STORAGE_S3_ACCESSKEY: s3-secret$access-key
      REGISTRY_STORAGE_S3_SECRETKEY: s3-secret$secret-key
    volumes:
    - name: auth
      configMap:
        name: auth
    - name: auth2
      configMap:
        name: auth2
    volumeMounts:
    - name: auth
      mountPath: /auth
  # metabase:
  #   imageName: "metabase/metabase:v0.46.5"
  #   containerPort: 3000
  #   replicas: 1
  #   host: metabase.shivamjha.com
  #   syncWave: 2
  #   port: 1001
