# Global value here is just for declaration so chart can be debugged in isolation,
# default global value will be set by parent chart and is initialised in bootstrap helm chart
global:
  env:
  branch:
  ingressConfig:
    ingress:
    annotations:
      cert-manager.io/cluster-issuer:
    tlsSecretName:

applications:
  hello-k8:
    imageName: "paulbouwer/hello-kubernetes:1.10.1"
    containerPort: 8080
    replicas: 2
    host: k3.shivamjha.com
    env:
      MESSAGE: "Hello from Helm - Prod Environment"
    syncWave: 1
    port: 1000
  # metabase:
  #   imageName: "metabase/metabase:v0.46.5"
  #   containerPort: 3000
  #   replicas: 1
  #   host: metabase.shivamjha.com
  #   syncWave: 2
  #   port: 1001
