{{ range $name, $value  := .Values.applications }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}-deployment
  namespace: {{ $name }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $value.syncWave | quote }}
spec:
  replicas: {{ $value.replicas }}
  selector:
    matchLabels:
      app: {{ $name }}-app
  template:
    metadata:
      name: {{ $name }}-pod
      labels:
        app: {{ $name }}-app
    spec:
      containers:
        - name: {{ $name }}-container
          image: {{ $value.imageName }}
          {{ if $value.volumeMounts }}
          volumeMounts:
            {{ toYaml $value.volumeMounts | nindent 12}}
          {{ end }}
          ports:
            - containerPort: {{ $value.containerPort }}
          {{ if or $value.env $value.secrets }}
          env:
            {{ if or $value.env }}
            {{ range $key, $val  := $value.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{ end }}
            {{ end }}
            {{ if or $value.secrets }}
            {{ range $key, $val  := $value.secrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  {{ $secrets := split "$" $val  }}
                  name: {{ $secrets._0 }}
                  key: {{ $secrets._1 }}
            {{ end }}
            {{ end }}
          {{ end }}
      {{ if $value.volumes }}
      volumes:
        {{ toYaml $value.volumes | nindent 8}}
      {{ end }}
{{ end }}