{{ range $name, $value  := .Values.applications }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}-deployment
  namespace: {{ $name }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $value.syncWave }}
spec:
  replicas: {{ $value.replicas }}
  selector:
    matchLabels:
      app: {{ $name }}-app
  template:
    metadata:
      name: {{ $name }}-pod
      labels:
        app: {{ $name }}-app
    spec:
      containers:
        - name: {{ $name }}-container
          image: {{ $value.imageName }}
          ports:
            - containerPort: {{ $value.containerPort }}
          {{ if $value.env }}
          env:
            {{ range $key, $val  := $value.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{ end }}
          {{ end }}
{{ end }}