{{ range $i, $app  := .Values.applications }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $app.name }}-ingress
  namespace: {{ $app.name }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $i | quote }}
    {{ toYaml $.Values.global.ingressConfig.annotations | nindent 4 }}
spec:
  ingressClassName: {{ $.Values.global.ingressConfig.ingress }}
  tls:
    - secretName: {{ $.Values.global.ingressConfig.tlsSecretName }}
      hosts:
        - {{ $app.host }}
  rules:
    - host: {{ $app.host }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ $app.name }}-service
              port:
                number: {{ add $i 1000 }}
{{ end }}
