{{ range $name, $value  := .Values.applications }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}-ingress
  namespace: {{ $name }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $name | quote }}
    {{ toYaml $.Values.global.ingressConfig.annotations | nindent 4 }}
spec:
  ingressClassName: {{ $.Values.global.ingressConfig.ingress }}
  tls:
    - secretName: {{ $.Values.global.ingressConfig.tlsSecretName }}
      hosts:
        - {{ $value.host }}
  rules:
    - host: {{ $value.host }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ $name }}-service
              port:
                number: {{ add $name 1000 }}
{{ end }}
