{{ range $name, $value  := .Values.applications }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-service
  namespace: {{ $name }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $value.syncWave }}
spec:
  selector:
    app: {{ $name }}-app
  type: ClusterIP
  ports:
    - port: {{ $value.port }}
      targetPort: {{ $value.containerPort }}
{{ end }}